server:
  port: 10800

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-r9alkf9p.gz.tencentcdb.com:10013/j-project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 150914
